In [1]:
documents = [
    "This is a list which containig sample documents.",
    "Keywords are important for keyword-based search.",
    "Document analysis involves extracting keywords.",
    "Keyword-based search relies on sparse embeddings."
]

In [2]:
query="keyword-based search"

In [3]:
import re
def preprocess_text(text):
    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text)
    return text

In [4]:
preprocess_documents=[preprocess_text(doc) for doc in documents]

In [5]:
preprocess_documents

['this is a list which containig sample documents',
 'keywords are important for keywordbased search',
 'document analysis involves extracting keywords',
 'keywordbased search relies on sparse embeddings']

In [6]:
preprocess_query=preprocess_text(query)

In [7]:
preprocess_query

'keywordbased search'

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [9]:
vector=TfidfVectorizer()

In [10]:
doc_embedding=vector.fit_transform(preprocess_documents)

In [11]:
doc_embedding.toarray()

array([[0.        , 0.        , 0.37796447, 0.        , 0.37796447,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.37796447, 0.        , 0.        , 0.37796447, 0.        ,
        0.        , 0.37796447, 0.        , 0.        , 0.37796447,
        0.37796447],
       [0.        , 0.4533864 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.4533864 , 0.4533864 , 0.        ,
        0.        , 0.35745504, 0.35745504, 0.        , 0.        ,
        0.        , 0.        , 0.35745504, 0.        , 0.        ,
        0.        ],
       [0.46516193, 0.        , 0.        , 0.46516193, 0.        ,
        0.        , 0.46516193, 0.        , 0.        , 0.46516193,
        0.        , 0.        , 0.36673901, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.43671931, 0.        , 0.        , 0.       

In [12]:
doc_embedding.toarray()[0]

array([0.        , 0.        , 0.37796447, 0.        , 0.37796447,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.37796447, 0.        , 0.        , 0.37796447, 0.        ,
       0.        , 0.37796447, 0.        , 0.        , 0.37796447,
       0.37796447])

In [13]:
query_embedding=vector.transform([preprocess_query])

In [14]:
query_embedding.toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.70710678, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.70710678, 0.        , 0.        ,
        0.        ]])

In [15]:
similarities=cosine_similarity(query_embedding,doc_embedding)

In [16]:
similarities

array([[0.        , 0.50551777, 0.        , 0.48693426]])

In [17]:
np.argsort(similarities)

array([[0, 2, 3, 1]])

In [18]:
rank_ind=np.argsort(similarities)[0][::-1]
rank_ind

array([1, 3, 2, 0])

In [19]:
rank_doc=[documents[i] for i in rank_ind]
rank_doc

['Keywords are important for keyword-based search.',
 'Keyword-based search relies on sparse embeddings.',
 'Document analysis involves extracting keywords.',
 'This is a list which containig sample documents.']

In [20]:
!pip install -qU pypdf langchain_community

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 309.7/309.7 kB 15.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 85.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.2/45.2 kB 3.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.9/50.9 kB 4.6 MB/s eta 0:00:00


In [10]:
from langchain_community.document_loaders import PyPDFLoader

In [11]:
filepath="/content/CS_DSAI_Roadmap.pdf"

In [12]:
docs=PyPDFLoader(filepath).load()

In [13]:
docs[0]

Document(metadata={'producer': 'Skia/PDF m102', 'creator': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Joplin/2.9.17 Chrome/102.0.5005.167 Electron/19.0.10 Safari/537.36', 'creationdate': '2023-05-19T07:15:42+00:00', 'moddate': '2023-05-19T07:15:42+00:00', 'source': '/content/CS_DSAI_Roadmap.pdf', 'total_pages': 7, 'page': 0, 'page_label': '1'}, page_content="CS_DSAI_Roadmap\nAbout\nThe sheet has been as a checkpoint/roadmap for students wanting to pursue CSE and DSAI. If you have any queries or want elaboration on any point, please contact me.\nContact Details - Name : Vaibhav Arora Phone : +91-8168401709 Email : vaibhavarora@iitbhilai.ac.in Note - You may also contact me for arrangement of course materials taught at IIT Bhilai.\nSDE targeted Tasks (CSE)\nSDE stands for Software development intern. It requires you to be good ith DSA and development. It is very important that CSE folks focus on their core subjects for this but there are plently of courses an

In [14]:
docs[0].metadata['total_pages']

7

In [15]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

In [16]:
text_spliter=RecursiveCharacterTextSplitter(chunk_size=200,chunk_overlap=40)

In [17]:
chunks=text_spliter.create_documents([docs[0].page_content])

In [18]:
chunks

[Document(metadata={}, page_content='CS_DSAI_Roadmap\nAbout\nThe sheet has been as a checkpoint/roadmap for students wanting to pursue CSE and DSAI. If you have any queries or want elaboration on any point, please contact me.'),
 Document(metadata={}, page_content='Contact Details - Name : Vaibhav Arora Phone : +91-8168401709 Email : vaibhavarora@iitbhilai.ac.in Note - You may also contact me for arrangement of course materials taught at IIT Bhilai.'),
 Document(metadata={}, page_content='SDE targeted Tasks (CSE)'),
 Document(metadata={}, page_content='SDE stands for Software development intern. It requires you to be good ith DSA and development. It is very important that CSE folks focus on their core subjects for this but there are plently of'),
 Document(metadata={}, page_content='for this but there are plently of courses and Problemsets online to learn from. Given 2 months of vacation, I would recommend the following'),
 Document(metadata={}, page_content="tasks -:\nStrivers' DSA Sh

In [23]:
!pip install -U sentence_transformers

In [19]:
from langchain_huggingface.embeddings import HuggingFaceEmbeddings

In [33]:
from google.colab import userdata

In [34]:
HF_TOKEN=userdata.get("hf")

In [ ]:
embeddings = HuggingFaceEmbeddings( model_name="BAAI/bge-base-en-v1.5")

In [ ]:
em_q=embeddings.embed_query("hello")
em_q[:5]

In [37]:
!pip install -qU "langchain-chroma>=0.1.2"

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.3/67.3 kB 3.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.5/19.5 MB 74.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 284.2/284.2 kB 1.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 65.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.6/101.6 kB 9.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.5/16.5 MB 78.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.6/65.6 kB 7.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 6.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.4/119.4 kB 10.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 201.6/201.6 kB 16.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 9.6 MB/s eta 

In [ ]:
from langchain_chroma import Chroma

vector_store = Chroma.from_documents(chunks,embeddings)

In [39]:
vectorstore_retreiver = vector_store.as_retriever(search_kwargs={"k": 3})

In [40]:
res=vectorstore_retreiver.invoke("what is SDE")

In [41]:
res

[Document(id='5869d7eb-d59e-4df1-a0e7-a6df4e856000', metadata={}, page_content='SDE stands for Software development intern. It requires you to be good ith DSA and development. It is very important that CSE folks focus on their core subjects for this but there are plently of'),
 Document(id='5882b142-4539-441b-8827-5f66f9b5c90c', metadata={}, page_content='SDE targeted Tasks (CSE)'),
 Document(id='d860503b-acd5-4a8a-b8bb-460a65e7a5f8', metadata={}, page_content="tasks -:\nStrivers' DSA Sheet - https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-\nsheet-2/\nStrivers SDE Sheet (if you have completed Networking, DBMS etc.) -")]

In [42]:
!pip install -qU rank_bm25

In [43]:
from langchain_community.retrievers import BM25Retriever
from langchain.retrievers import EnsembleRetriever

In [44]:
keyword_retriver=BM25Retriever.from_documents(chunks)

In [46]:
keyword_retriver.k=3

In [47]:
keyword_retriver.invoke("what is SDE")

[Document(metadata={}, page_content='SDE targeted Tasks (CSE)'),
 Document(metadata={}, page_content='SDE stands for Software development intern. It requires you to be good ith DSA and development. It is very important that CSE folks focus on their core subjects for this but there are plently of'),
 Document(metadata={}, page_content="tasks -:\nStrivers' DSA Sheet - https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-\nsheet-2/\nStrivers SDE Sheet (if you have completed Networking, DBMS etc.) -")]

In [54]:
ensemble_retriever = EnsembleRetriever(retrievers=[vectorstore_retreiver,keyword_retriver],weights=[0.5, 0.5])

In [55]:
ensemble_retriever.invoke("what is SDE")

[Document(id='5869d7eb-d59e-4df1-a0e7-a6df4e856000', metadata={}, page_content='SDE stands for Software development intern. It requires you to be good ith DSA and development. It is very important that CSE folks focus on their core subjects for this but there are plently of'),
 Document(id='5882b142-4539-441b-8827-5f66f9b5c90c', metadata={}, page_content='SDE targeted Tasks (CSE)'),
 Document(id='d860503b-acd5-4a8a-b8bb-460a65e7a5f8', metadata={}, page_content="tasks -:\nStrivers' DSA Sheet - https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-\nsheet-2/\nStrivers SDE Sheet (if you have completed Networking, DBMS etc.) -")]

In [56]:
model_name = "HuggingFaceH4/zephyr-7b-beta"

In [71]:
!pip install -U bitsandbytes

  Using cached bitsandbytes-0.46.1-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.1/62.1 kB 5.1 MB/s eta 0:00:00
  Using cached setuptools-80.9.0-py3-none-any.whl.metadata (6.6 kB)
Using cached bitsandbytes-0.46.1-py3-none-manylinux_2_24_x86_64.whl (72.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.9/16.9 MB 54.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 821.2/821.2 MB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 393.1/393.1 MB 4.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 121.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 95.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 897.7/897.7 kB 55.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 571.0/571.0 MB 888.1 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.2/200.2 MB 6.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1

In [59]:
!pip install -qU accelerate

In [60]:
import torch
from transformers import ( AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, pipeline, )
from langchain_huggingface.llms import HuggingFacePipeline

In [68]:
# function for loading 4-bit quantized model
def load_quantized_model(model_name: str):
    """
    model_name: Name or path of the model to be loaded.
    return: Loaded quantized model.
    """
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_use_double_quant=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16,
    )

    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        torch_dtype=torch.bfloat16,
        quantization_config=bnb_config,
    )
    return model

In [62]:
# initializing tokenizer
def initialize_tokenizer(model_name: str):
    """
    model_name: Name or path of the model for tokenizer initialization.
    return: Initialized tokenizer.
    """
    tokenizer = AutoTokenizer.from_pretrained(model_name, return_token_type_ids=False)
    tokenizer.bos_token_id = 1  # Set beginning of sentence token id
    return tokenizer

In [69]:
tokenizer = initialize_tokenizer(model_name)

In [ ]:
model = load_quantized_model(model_name)

In [ ]:
pipeline = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    use_cache=True,
    device_map="auto",
    max_length=2048,
    do_sample=True,
    top_k=5,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
    pad_token_id=tokenizer.pad_token_id,
)

In [ ]:
llm = HuggingFacePipeline(pipeline=pipeline)

In [ ]:
from langchain.chains import RetrievalQA


In [ ]:
normal_chain = RetrievalQA.from_chain_type(
    llm=llm, chain_type="stuff", retriever=vectorstore_retreiver
)

In [ ]:
hybrid_chain = RetrievalQA.from_chain_type(
    llm=llm, chain_type="stuff", retriever=ensemble_retriever
)

In [ ]:
response1 = normal_chain.invoke("What is Abstractive Question Answering?")
response1

In [ ]:
response2 = hybrid_chain.invoke("What is Abstractive Question Answering?")
response2